### ISSUE TITLE
Show the boulder list with items from the database

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/capstone-heel-hook#1]
## Value statement - a requirement, not a solution
As a climber
I want to retrieve a list of active boulders  
so that I can find a specific boulder

## Description (Text, Scribble, Wireframe, Design)

This does not need to look pretty at first. This is mainly to get the back end running with the front end.

## Acceptance criteria
The boulder list includes at least the following boulder details:
- [ ] ID
- [ ] Name
- [ ] Level
- [ ] Handle color
- [ ] Sector
- [ ] Likes*
- [ ] Multiplier*
Additionally each list item has a clickable button which will link to the "My climbed boulder" page

## Tasks
- [ ] Set up database mongoDB Atlas
- [ ] Set up boulder collection with mongoose schema
- [ ] Set up "Find my boulder" page on front end
- [ ] Create boulder component
- [ ] Fetch boulder from database
- [ ] Render list of boulders

## Size
large

**Comment by mpagels** [comment]
Good start here Antje. But I think the story is too big to be just one. You have to work on the backend and the frontend at the same time for this story.

I would separate both parts to different stories.

The frontend story should just render a `hardcoded` list of active boulder on the frontend. The good thing is, you don't need a backend for that and you can focus just on the frontend and when you're done with it, you have something that is working on the frontend. After that, you can focus just on the backend story and implement the models etc. At the end, you have to make just an API call from the frontend to receive the data.

What do you think about it?


## And the `Acceptance criterias` are used this way:
### Frontend part:
- You write here what should happen, that the story is complete. (The more details, the better)
- You write **not**: "later a rendered button is maybe doing this, maybe?"
- Because this button lives in your feature and is doing nothing for the user for maybe years 

I would write for example
- [ ] when the frontend starts, a `hardcoded` list of boulders are rendered as a list of `cards` (see scribble of card in the description part of the story)
every card should contain the following information:
- [ ] ID
- [ ] Name
- [ ] Level
- [ ] Handle color
- [ ] Sector
- [ ] Likes*
- [ ] Multiplier*
- [ ] and a `show more` button
- [ ] the card shows only the `name`, `level` and `handle color` information
- [ ] when `clicking` the button the card should expand and the `rest` of the information are shown
- [ ] the label of the button is changing from `show more` to `close`
- [ ] when the card is `expaned` and the `button` is clicked again, the card should close and the additional information are not showing anymore
- [ ] the label of the button is changing from `close` to `show more`

### Backend part:

- [ ] when hitting the `/` route on the backend it is returning a list of `active` boulder as a `json` object

**Comment by mpagels** [comment]
You don't need a `header` & `footer` component here for the story. Just render a list of cards that represents a boulder.

I don't understand what the `*` means on the `boulder details` (Multiplier*) I would recommend adding this kind of information to the story.

I also recommend adding the task `storybook` & `testing`  to the tasks part. This happy tasks should not be forgotten. ;-)

Besides that, the story looks good. When implemented the suggested changes, then it is a GO! Awesome.
