### ISSUE TITLE
1 - Build app skeleton

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/capstone-heel-hook#2]
## Value statement - a requirement, not a solution

As a climber
I need to look at a clearly structured app
so that I learn quickly how to interact with the app.

## Description (Text, Scribble, Wireframe, Design)

<img width="317" alt="Screenshot 2022-04-26 at 11 19 54" src="https://user-images.githubusercontent.com/94105745/165267457-2a4a5368-5055-4c9a-ae6b-f9d7c2aa7044.png">

## Acceptance criteria
App skeleton should include
- [ ] header which will show a header for each page
- [ ] main area which will hold content for the different pages
- [ ] footer which will serve for the main pages navigation
- [ ] At this stage no content or only dummy content needs to be shown

## Tasks
- [ ] Build front end app skeleton without any content
- [ ] Header and Footer should be sticky

## Size
small

**Comment by mpagels** [comment]
Pls [check](https://github.com/PulexIrritans/capstone-heel-hook/issues/1#issuecomment-1108686078).

The `acceptance criterias` are not enough. You should add
- what links should the `navbar` contain?
- do you need every link in the `navbar` right now? Remember, just implement features that actively helping the user using your app. It makes no sense insert a `profile` link to the `navbar` when there is no `profile` page
- explain what happens, when you click on a link in the `navbar`

The scribbles could be more detailed. Or should only contain things that are important to the story.

**Comment by mpagels** [comment]
Hey Antje,
unfortunately, that is not a story. The feature has no impact on the user. The user sees an empty page.
- The `header` & `footer` components should be a separate `user story`

If you want, we can talk about it in a private room. The story #1 is a way better start for the develop process.
