### ISSUE TITLE
Show boulder details on "Add my climbed boulder" page

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/capstone-heel-hook#3]
## Value statement - a requirement, not a solution

As a climber 
I want to see more details of a selected boulder 
so that I can be sure to be looking at the correct boulder 

## Description (Text, Scribble, Wireframe, Design)

<img width="329" alt="Screenshot 2022-04-24 at 20 52 41" src="https://user-images.githubusercontent.com/94105745/164991902-21df4e59-f426-4a10-a38f-84e38e8eff23.png">

## Acceptance criteria
A more detailed view on a boulder should include
- [ ] ID
- [ ] Name
- [ ] Level
- [ ] Handle color
- [ ] Sector
- [ ] Weighting
- [ ] Setter name
- [ ] picture of start handles

## Tasks
- [ ] Reuse boulder component and add detailed state 
- [ ] Style boulder component for short and detailed view

## Size
medium
