### ISSUE TITLE
Climbed boulder form

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/capstone-heel-hook#4]
## Value statement - a requirement, not a solution

As a climber
I want to enter data for a climbed boulder 
so that this can be used to calculate rankings, scores, stats etc.

## Description (Text, Scribble, Wireframe, Design)

<img width="417" alt="Screenshot 2022-04-24 at 21 41 12" src="https://user-images.githubusercontent.com/94105745/164993656-716a273d-a60a-48ea-83d8-a1558cba6a7a.png">

## Acceptance criteria

If there are dates already saved for this climber and boulder then these dates should show here as values for the form fields.
This should be a validated form with the following input fields.
- [ ] Boulder ID (pre-filled if boulder was selected from list)
- [ ] Projected (Toggle)
- [ ] Zone, Top, Flash (Radio Button)
- [ ] Attempts (number)
- [ ] Level Feedback: too easy, just right, too hard (Radio Button)
- [ ] Like (Checkbox)

## Tasks
- [ ] Create Climbed Boulder Form Component
- [ ] Setup all input fields
- [ ] Style form
- [ ] Post Climbed_Boulder to DB on Submit
- [ ] Calculate new boulder weighting and update weighting in boulder document

## Size
large
