### ISSUE TITLE
Climber profile page

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/capstone-heel-hook#5]
## Value statement - a requirement, not a solution

As a climber
I want to see and possibly update my climber profile
so that the provided data can be used to generate individual stats and scores 

## Description (Text, Scribble, Wireframe, Design)

<img width="324" alt="Screenshot 2022-04-25 at 08 36 17" src="https://user-images.githubusercontent.com/94105745/165033428-ffbed2a9-75aa-43ee-9b36-d5f83f002ddb.png">

## Acceptance criteria
User profile should include information about
- [ ] User name*
- [ ] First name*
- [ ] Last name*
- [ ] Profile picture (should be static at first)
- [ ] Gender
- [ ] Birthday
- [ ] Ape index
- [ ] Height
- [ ] Start date of being a climber

- [ ] The information should be editable inside a form
- [ ] The form should be created as a component
- [ ] On Submit/ Save the profile information should be patched to the database and the climber profile should be updated accordingly

## Tasks
- [ ] Create user profile component
- [ ] Set up form with form fields
- [ ] Use form validation
- [ ] Make sure that saved data is displayed as default value
- [ ] implement Patch data for climber
- [ ] Style component

## Size
medium

**Comment by mpagels** [comment]
- The `gender`, `birthday`, `ape index` and `started bouldering` inputs, what type of types you want to save this in your database?
`strings`, `numbers`, `date` ? How is this data displayed in the frontend?
- which input is `required` ?
- what happens, when inputs are missing?

- what happens, when I go simple to the `profile` page? Is the `form` already open and I can type something? Or is my data just rendered and there is a button for editing (and then the form is rendered) ?
