### ISSUE TITLE
Fetch boulder list from database collection

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/capstone-heel-hook#6]
## Value statement - a requirement, not a solution
As a developer
I want to fetch the boulder list from the db
so that this can be dynamically changed in the future

## Acceptance criteria
- There is a working connection between frontend and backend
- The list of boulders can be fetched from the database
- Each document from the collection is rendered into one boulder card item
- The information are displayed correctly using the object properties

## Tasks
- [ ] Set up database mongoDB Atlas
- [ ] Set up boulder collection with mongoose schema
- [ ] Add three boulder documents so that these can be used for testing
- [ ] Fetch boulder from database and and render the list of boulders from the database fetch

## Size
medium

**Comment by mpagels** [comment]
Hey Antje,
unfortunately, the `acceptance criteria` are not correct used here.

I would add 
- There is a working connection between frontend and backend
- The list of boulders can be fetched from the database
- Each document from the collection is rendered into one boulder card item
- The information are displayed correctly using the object properties
to the `Description part` of the story

The `acceptance criteria` should look like this:

- [ ] when going to `/` the server response with a list of boulder objects
- [ ] a boulder object looks like this
```json
{ "key" : "value" }
```

And you should ask yourself if the connection from backend to frontend is worth another story, or you put it in the `task` part.
