### ISSUE TITLE
4 - Add link to "Add my climbed boulder" to each boulder card

### ISSUE THREAD

**Issue by PulexIrritans** [PulexIrritans/capstone-heel-hook#7]
## Value statement - a requirement, not a solution
As a climber
I want to be able to select a specific boulder from the list 
so that a new page "Add my climbed boulder" is opened

## Description (Text, Scribble, Wireframe, Design)

The new page will be used to see more details for a specific boulder plus for entering boulder climb data. This user story however does for now only include the linking to this new page. In the scribble you can see the final functions of the "Add my climbed boulder" page. The functionalities will be covered in the next user stories.
<img width="698" alt="Screenshot 2022-04-26 at 11 38 17" src="https://user-images.githubusercontent.com/94105745/165271015-501d970a-12aa-4f94-8a31-a1fe1259ef3e.png">

## Acceptance criteria
- [ ] In the list of boulders on the "Find my boulder" page the user can select one of the boulders by clicking on a button "Climb"
- [ ] The button will bring the user to a new page "Add my climbed boulder".
- [ ] The pages "Find my boulder" and "Add my climbed boulder" can also be selected using the navigation in the footer.

## Tasks
- [ ] Install react-router
- [ ] Implement a navigation component.
- [ ] Implement routes and links for the first two pages "Find my boulder" and "Add my climbed boulder"; routes in the main section of the app, links in the navigation component and for the "Climb" button.

## Size
small

**Comment by mpagels** [comment]
Hey Antje, this `story` is too big. It seems that it contains `three` stories. A `navigation` part, a `save` part and a `show` part. I would recommend making this `story` smaller. (You know the drill)

You could rewrite the story to just open a `boulder card` to show more details (and omit the `navigation` part)

When you want to implement the `navigation` as well, you should think about, how to go back to the `main` page.

You definitely don't need a `NavBar` in this story.

By the way, I know you're good, but evaluate the story as `small` is very optimistic ;-) 

And here is the obligatory note:
- I also recommend adding the task storybook & testing to the tasks part. This happy tasks should not be forgotten. ;-)

And as always, if you want to talk about it, just slack me.
